config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'pages#home'

  devise_for :users,
       :path => '' ,
       :path_names => {:sign_in => 'login', :sign_out => 'logout', :edit => 'profile'},
       :controllers => {:omniauth_callbacks => 'omniauth_callbacks',
                :registrations => 'registrations'
              }


 resources :users, only: [:index, :show] do

 end
 resources :revisers
  # get '/premium/', to: 'revisers#show'
 resources :photos
 resources :pages

 #make sure to change this to user!!! instead of reservations!!!
resources :reviser do
  resources :reservations, only: [:create, :edit, :update]
end


get '/preload' => 'reservations#preload'
get '/preview' => 'reservations#preview'

post '/sent' => 'reservations#sent'
get '/sent' => 'reservations#sent'

post '/notify' => 'reservations#notify'
# get '/mypayments' => 'reservations#your_essays'
get '/received' => 'reservations#received'



get '/school_list' => 'pages#school_list'
get '/about' => 'pages#about'

get '/mentor' => 'pages#mentor'
# get '/payment' => 'pages#payment'
# get '/revisers/11', to: 'patients#show', as: 'payment'

get '/how-to-use/kr' => 'pages#korea'
get '/how-to-use/en' => 'pages#english'
get '/how-to-use/jp' => 'pages#japan'
get '/how-to-use/ch' => 'pages#china'





resources :revisers do
  resources :reviews, only: [:create, :destroy]
end


 resources :suggestions do
  get :autocomplete_user_country, :on => :collection
  get :autocomplete_user_company_name, :on => :collection

  get :autocomplete_user_city, :on => :collection
  get :autocomplete_user_school, :on => :collection
  get :autocomplete_user_major, :on => :collection
 end



 # Community
 resources :boards do
   resources :posts do
       resources :comments
   end
 end
 resources :posts do
     resources :comments
   end

# Messages

 resources :conversations, only: [:index, :show, :destroy] do
   member do
     post :reply
   end
 end
 resources :conversations, only: [:index, :show, :destroy] do
   member do
     post :restore
   end
 end
 resources :conversations, only: [:index, :show, :destroy] do
     collection do
       delete :empty_trash
     end
   end

 resources :conversations, only: [:index, :show, :destroy] do
   member do
     post :mark_as_read
   end
 end
 resources :messages, only: [:new, :create]



 resources :posts do
  resources :comments
  resources :places
end



end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  # before_action :authenticate_user!

  def new
    @chosen_recipient = User.find_by(id: params[:to].to_i) if params[:to]
  end

  def create

    recipients = User.where(id: params['recipients'])
    conversation = current_user.send_message(recipients, params[:message][:body], params[:message][:subject]).conversation
    flash[:success] = "Message has been sent!"
    redirect_to conversation_path(conversation)
    # if current_user.access == false
    #   if current_user.messages.where("created_at::date = ?", Date.today).count >= 10
    #     respond_to do |format|
    #       format.html { redirect_to premium_path, notice: 'Want to send more Messages? Become Premium member!' }
    #       format.json { head :no_content }
    #     end
    #   else
    #     conversation = current_user.send_message(recipients, params[:message][:body], params[:message][:subject]).conversation
    #     flash[:success] = "Message has been sent!"
    #     redirect_to conversation_path(conversation)
    #   end
    # else
    #   conversation = current_user.send_message(recipients, params[:message][:body], params[:message][:subject]).conversation
    #   flash[:success] = "Message has been sent!"
    #   redirect_to conversation_path(conversation)
    # end

    # @message =  current_user.send_message(recipients, params[:message][:body],params[:message][:subject])
    # if @message.receiver.messages.count >= 6
    #   respond_to do |format|
    #     format.html { redirect_to premium_path, notice: 'Want to send more Messages? Become Premium member!' }
    #     format.json { head :no_content }
    #   end
    #
    # else
    #   flash[:success] = "Message has been sent!"
    #   redirect_to conversation_path(@message)
    # end
end
end

private

  def premium


  end

app/helpers/messages_helper.rb
module MessagesHelper
  def recipients_options(chosen_recipient = nil)
  s = ''
  User.all.each do |user|
    s << "<option value='#{user.id}' #{'selected' if user == chosen_recipient}>#{user.username}</option>"
    end
    s.html_safe
  end
end

app/views/messages/create.html.erb
<h1>Messages#create</h1>
<p>Find me in app/views/messages/create.html.erb</p>

app/views/messages/new.html.erb
<div class = "container3">
<%= form_tag messages_path, method: :post do %>


  <h5>
    <!-- <%= select_tag 'recipients', recipients_options(@chosen_recipient), multiple: true, style: 'visibility:hidden' %> -->
  </h5>
  <h3 style="color:#fff;">
    메세지를 보내시면 멘토분의 이메일로 연락이 갑니다! <br>
    Message to :  <%= @chosen_recipient.fullname %>
  </h3>
  <div class="form-group" >
    <%= label_tag 'message[subject]', 'Title(Say "안녕하세요!")', style: 'color:#fff;font-size:2rem;' %>
    <%= text_field_tag 'message[subject]', @chosen_recipient.fullname + "님, 안녕하세요", class: 'form-control'%>
  </div>

  <div class="form-group">
    <%= label_tag 'message[body]', '' %>
    <%= text_area_tag 'message[body]', nil, cols: 3, style: 'height:200px;',class: 'form-control', required: true, :placeholder => "ex: 안녕하세요,

    선배님이 유학하고 계신 학교에 지원하려는데 다른 곳과 고민중입니다... 학교 생활에 만족하고 계신가요?

    졸업하고 어떤 진로로 나아갈 수 있나요?

    제 SOP 한번 봐주실 수 있을까요?" %>
  </div>


  <%= submit_tag 'Send', class: 'btn btn-primary' %>

  <div class="form-group" style="height: 3rem;">
    <%= label_tag 'recipients', '' %>
    <%= select_tag 'recipients', recipients_options(@chosen_recipient), multiple: true, class: 'form-control chosen-it', style: "visibility:hidden" %>
  </div>
<% end %>
  </div>



  <div class="container3" style="min-width: 1100px;" >
  <div class="panel panel-default">
  		<div class="panel-body">
  <div id="wrap">
  	<div class="row" style="" >






  		<div class="col-md-4"  style="height:100%;">
  			<!-- Make an if statement for online and offline -->
  <div class="prof-contain" style="background-color:#F8F8F8;border-radius: 4px;padding-bottom:20px;padding-top:20px;">
  		<div class="row center">
        <!-- <% if @chosen_recipient.online? %>
        <div class="btn btn-block" id="available">
  				Online Now
  			</div>
  			<% else %>
  			<div class="btn btn-block" id="unavailable" style="background-color:#990000;">
  				Offline
  			</div>
  			<% end %> -->

  			<div id="contain-pic-show">
  				<div class="thumbnail-show" style="width:300px;height:300px;overflow:hidden;background-color:black;">
  					<!-- <%= image_tag @chosen_recipient.avatar.url(:medium), :id => "image-tag", class: "portrait" %> -->
            <!-- <%= image_tag "http://graph.facebook.com/#{@chosen_recipient.uid}/picture?type=large" %> -->
            <% if @chosen_recipient.avatar? %>
              <%= image_tag @chosen_recipient.avatar.url(:medium), :id => "image-tag", class: "portrait" %>
            <% else %>
              <% if @chosen_recipient.uid? %>
              <%= image_tag "http://graph.facebook.com/#{@chosen_recipient.uid}/picture?type=large" %>
              <% end %>
            <% end %>

  				</div>
  				</div>
  				<!-- <div id="average_rating"></div>
  				<script>
  	$('#average_rating').raty({
  		path: '/assets',
  		readOnly: true,
  		score:
      <% @chosen_recipient.revisers.each do |reviser| %>
      <%= reviser.reviews.average(:star) %>
      <% end %>
  	});
  </script> -->

  			</div>

  			<div class="row " style="margin-left:20px;">
          <!-- *************************Premium*************************** -->



            <!-- *************************Premium*************************** -->
            <div class="row" >
              <div class="col-xs-3" >
                <h2 style="font-size:20px;margin:0 auto;">Name:</h2>
              </div>
              <% if @chosen_recipient.fullname != nil %>
              <div class="col-xs-8" style="margin-left:30px;">
                <h><%= @chosen_recipient.fullname %></h>
              </div>
              <% else %>
              <div class="col-xs-8" style="margin-left:30px;height:20px;line-height:25px;">
                <h>N/A</h>
              </div>
            <% end %>
            </div>
          <!-- <div class="row" >
  					<div class="col-xs-3" >
  						<h2 style="font-size:20px;margin:0 auto;">Country:</h2>
  					</div>
  					<% if @chosen_recipient.country != nil %>
  					<div class="col-xs-8" style="margin-left:30px;">
  						<h><%= @chosen_recipient.country %></h>
  					</div>
  					<% else %>
  					<div class="col-xs-8" style="margin-left:30px;height:20px;line-height:25px;">
  						<h>N/A</h>
  					</div>
  				<% end %>
  				</div> -->


  				<div class="row">
  					<div class="col-xs-3">
  						<h2 style="font-size:20px;margin:0 auto;">University:</h2>
  					</div>
  					<% if @chosen_recipient.school != nil %>
  					<div class="col-xs-8" style="margin-left:30px;">
  						<h><%= @chosen_recipient.school %></h>
  					</div>
  					<% else %>
  					<div class="col-xs-8" style="margin-left:30px;height:20px;line-height:25px;">
  						<h>N/A</h>
  					</div>

  				<% end %>
  				</div>
          <div class="row" >
  					<div class="col-xs-3" >
  						<h2 style="font-size:20px;margin:0 auto;">Major:</h2>
  					</div>
  					<% if @chosen_recipient.major != nil %>
  					<div class="col-xs-8" style="margin-left:30px;">
  						<h><%= @chosen_recipient.major %></h>
  					</div>
  					<% else %>
  					<div class="col-xs-8" style="margin-left:30px;height:20px;line-height:25px;">
  						<h>N/A</h>
  					</div>
  				<% end %>
  				</div>




          <!-- <% if @chosen_recipient.schoolemail != nil %>
  				<div class="row" >
  					<div class="col-xs-3" >
  						<h2 style="font-size:20px;margin:0 auto;">Schoolemail:</h2>
  					</div>
  					<div class="col-xs-8" style="margin-left:30px;height:20px;line-height:25px;">
  						<h><%= @chosen_recipient.cut_email %></h>
  					</div>
  				</div>
  				<% end %> -->



          <!-- <% if @chosen_recipient.city != nil %>
  				<div class="row">
  					<div class="col-xs-3">
  						<h2 style="font-size:20px;margin:0 auto;">City:</h2>
  					</div>
  					<div class="col-xs-8" style="margin-left:30px;height:20px;line-height:25px;">
  						<h><%= @chosen_recipient.city %></h>
  					</div>
  				</div>
  				<% end %> -->

  <% if @chosen_recipient.occupation != nil %>
  				<!-- <div class="row" >
  					<div class="col-xs-3" >
  						<h2 style="font-size:20px;margin:0 auto;margin-right:10px;">Occupation:</h2>
  					</div>
  					<div class="col-xs-8" style="margin-left:30px;height:20px;line-height:25px;">
  						<h style=""><%= @chosen_recipient.occupation %></h>
  					</div>
  				</div> -->
  				<% end %>

  <% if @chosen_recipient.company_name != nil %>
  				<div class="row" >
  					<div class="col-xs-3" >
  						<h2 style="font-size:20px;margin:0 auto;">Company:</h2>
  					</div>
  					<div class="col-xs-8" style="margin-left:30px;height:20px;line-height:25px;">
  						<h><%= @chosen_recipient.company_name %></h>
  					</div>
  				</div>
  				<% end %>
  <% unless @chosen_recipient.kakao == nil || @chosen_recipient.kakao == "" || @chosen_recipient.kakao == " " %>

          <div class="row">
            <div class="col-xs-3">
              <h2 style="font-size:20px;margin:0 auto;">Kakao:</h2>
            </div>
            <div class="col-xs-8" style="margin-left:30px;height:20px;line-height:25px;">
              <h><%= @chosen_recipient.kakao %></h>
            </div>
          </div>
          <% end %>
  			</div>


  		</div>

  </div>

  		<div class="col-md-8">

  			<div class="row">

          				<div class="col-sm-12">
          					<h2 style="font-size:40px;"> <%= @chosen_recipient.fullname %></h2>
          				</div>
          				<div class="row center">
          					<!-- <div class="col-sm-4">
          						<div class="msg-btn">
          							<%= link_to 'Send message', new_message_path(to: @chosen_recipient.id), class: 'btn btn-primary' %>
          						</div>
          					</div> -->
          					<div class="col-sm-4">
          						<div class="msg-btn">
          							<% @chosen_recipient.revisers.each do |reviser| %>
                        <%= link_to reviser do %>

                        <div class="btn btn-primary">상담 예약 결제</div>
                        <% end %>

                          <!-- <% if reviser.active == true %>
          								<%= link_to reviser do %>

          								<div class="btn btn-primary">Make an Appointment</div>
          								<% end %>

          								<% else %>
          								<div class="btn btn-default disabled" style="margin-top:0;">Mentor Service Not Available</div>



          								<% end %> -->
          							<% end %>
          						</div>
          					</div>
          				</div>
  				<div class="row col-sm-10" style="margin-left:75px;margin-top:20px;">
  				<label style="font-weight:bold;font-size:2.4rem;border-bottom:1px solid #333;">About Me</label>
  					<div class="description" style="word-wrap:break-word;">
  					<% if @chosen_recipient.description != nil %>
  						<%= markdownify @chosen_recipient.description %>
  						<% else %>
  						<p style="overflow:auto"> There is no description...... </p>
  						<% end %>
  					</div>
  				</div>
  			</div>
<!-- LANGUAGE, SPECIALTIES-->
        <!-- <div class="row col-md-12" style="min-height:10rem;max-height:20rem;margin-top:15px;min-width:600px;" id="introduction">

          <div class="col-xs-6" style="overflow:scroll;">
            <% if @chosen_recipient.languages != nil %>
            <h3> Languages </h3>
                <% @chosen_recipient.languages.each do |f| %>

                <p style="">- <%= f.language  %></p>


                <% end %>

            <% else %>
            <h3> Languages </h3>
            Not Added Yet


            <% end %>


          </div>

          <div class="col-xs-6" style="overflow:scroll;">
            <% if @chosen_recipient.specialties != nil %>
            <h3> Specialties </h3>
            <% @chosen_recipient.specialties.each do |f| %>

            <p style="">- <%= f.specialty  %></p>

            <% end %>
            <% else %>
            <h3> Specialties </h3>
            Not Added Yet


            <% end %>
          </div>
        </div> -->
        <!--  SCHOLARSHIPS-->
        <% if @chosen_recipient.scholarships != nil %>

        <div class="row " style="margin-top:15px;min-width:300px;" id="introduction">
          <div class="col-md-12">

              <h3 style="margin-bottom: 2rem;"> Scholarships </h3>
              <% @chosen_recipient.scholarships.each do |f| %>

              <p style="">- <%= f.name  %></p>
              <% end %>





          </div>
        </div>
        <% else %>
        <% end %>
  			<div class="row" style="margin-top:15px;min-width:600px;" id="introduction">

          <!-- WORK EXPERIENCE -->
  				<!-- <div class="col-xs-12" style="height:25rem;max-height:50rem;overflow:auto">
  					<% if @chosen_recipient.occupation_details != nil %>
  					<h3> Work/School Experience </h3>

  					<p style="overflow:auto"><%= markdownify @chosen_recipient.occupation_details %></p>
  					<% else %>

  					<% end %>
  				</div> -->
          <% if @chosen_recipient.educations != nil %>

  				<div class="col-xs-12" style="height:25rem;max-height:50rem;overflow:auto">

  					<!-- <% if @chosen_recipient.school_description != nil %>
  					<h3> Education</h3>

  					<p style="overflow:auto"><%= markdownify @chosen_recipient.school_description %></p>
            <% else %>

  					<% end %> -->

            <h3> Education & Experience</h3>

              <% @chosen_recipient.educations.each do |f| %>


              <p style="">- <%= f.education  %></p>
              <% end %>




  				</div>
          <% else %>

          <% end %>

  			</div>




        <!--  REVIEWS-->
  <!--
  <div class="col-sm-12" style="margin-top:40rem;margin-bottom:40px;">

  </div> -->




  		</div>



  	</div>

  </div>

  </div>
  </div>


  </div>