config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'pages#home'

  devise_for :users,
       :path => '' ,
       :path_names => {:sign_in => 'login', :sign_out => 'logout', :edit => 'profile'},
       :controllers => {:omniauth_callbacks => 'omniauth_callbacks',
                :registrations => 'registrations'
              }


 resources :users, only: [:index, :show] do

 end
 resources :revisers
  # get '/premium/', to: 'revisers#show'
 resources :photos
 resources :pages

 #make sure to change this to user!!! instead of reservations!!!
resources :reviser do
  resources :reservations, only: [:create, :edit, :update]
end


get '/preload' => 'reservations#preload'
get '/preview' => 'reservations#preview'

post '/sent' => 'reservations#sent'
get '/sent' => 'reservations#sent'

post '/notify' => 'reservations#notify'
# get '/mypayments' => 'reservations#your_essays'
get '/received' => 'reservations#received'



get '/school_list' => 'pages#school_list'
get '/about' => 'pages#about'

get '/mentor' => 'pages#mentor'
# get '/payment' => 'pages#payment'
# get '/revisers/11', to: 'patients#show', as: 'payment'

get '/how-to-use/kr' => 'pages#korea'
get '/how-to-use/en' => 'pages#english'
get '/how-to-use/jp' => 'pages#japan'
get '/how-to-use/ch' => 'pages#china'





resources :revisers do
  resources :reviews, only: [:create, :destroy]
end


 resources :suggestions do
  get :autocomplete_user_country, :on => :collection
  get :autocomplete_user_company_name, :on => :collection

  get :autocomplete_user_city, :on => :collection
  get :autocomplete_user_school, :on => :collection
  get :autocomplete_user_major, :on => :collection
 end



 # Community
 resources :boards do
   resources :posts do
       resources :comments
   end
 end
 resources :posts do
     resources :comments
   end

# Messages

 resources :conversations, only: [:index, :show, :destroy] do
   member do
     post :reply
   end
 end
 resources :conversations, only: [:index, :show, :destroy] do
   member do
     post :restore
   end
 end
 resources :conversations, only: [:index, :show, :destroy] do
     collection do
       delete :empty_trash
     end
   end

 resources :conversations, only: [:index, :show, :destroy] do
   member do
     post :mark_as_read
   end
 end
 resources :messages, only: [:new, :create]



 resources :posts do
  resources :comments
  resources :places
end



end

app/models/reviser.rb
class Reviser < ActiveRecord::Base
  belongs_to :user

  has_many :reservations
  has_many :reviews

  # validates :description, presence: true, length: {maximum: 500, minimum:10}
  # validates :average_time, presence: true

  # validates :max_pages, presence: true
  # validates :price_per, presence: true
  # validates :paypal, presence: true


  validates :essay_type, uniqueness: { scope: :user_id }

  def average_rating
  	reviews.count == 0 ? 0 : reviews.average(:star).round(2)
  end

  def reviser_profit
    self.price_per * self.reservations.count
  end

end

app/controllers/revisers_controller.rb
class RevisersController < ApplicationController
  before_filter :require_permission, only: [:edit, :update, :destroy]

before_action :set_reviser, only: [:show, :edit, :update, :destroy]
before_action :authenticate_user!


  def index
    @revisers = current_user.revisers
  end

  def show
    @booked = Reservation.where("reviser_id = ? AND user_id = ?", @reviser.id, current_user.id).present? if current_user
    @reviser = Reviser.find(params[:id])
    @reviews = @reviser.reviews
    @revisers = current_user.revisers

   end


  def new
    @reviser = current_user.revisers.build
   # @reviser = current_user.build_reviser(params[:reviser])

  end

  def create
    @reviser = current_user.revisers.build(reviser_params)

    if @reviser.save
      redirect_to edit_user_registration_path(current_user.id), notice: "Became A Mentor!!"
    else
      render :new
    end
  end

  def edit
    if current_user.id == @reviser.user.id


    else
      redirect_to edit_user_registration_path(current_user.id), notice: "You dont have permission to see this"
    end
  end

  def update

    if @reviser.update(reviser_params)
      @reviser.save
      redirect_to edit_user_registration_path(current_user.id), notice: "Updated"
    else
      render :edit
    end
  end

    def destroy
      @reviser.destroy
      respond_to do |format|
        format.html { redirect_to root_path, notice: 'Mentor Service was successfully destroyed.' }
        format.json { head :no_content }
      end
    end


private

    def set_reviser

      @reviser = Reviser.find(params[:id])
    end

    def reviser_params
      params.require(:reviser).permit(:description, :average_time, :essay_type, :max_pages, :price_per, :active, :paypal)
    end
    def require_permission
      @reviser = current_user.revisers.last
      if current_user.id != @reviser.user_id
        redirect_to root_path, notice: "Sorry, you're not allowed"
      end

    end
end

app/helpers/revisers_helper.rb
module RevisersHelper
end

app/views/revisers/_essayiconsdirect.html.erb
<% if @reviser.try(:essay_type) == "College Applications" %>
					<i class="fa fa-wpforms" aria-hidden="true" style="font-size:60px;color:#45d1b8;"></i>
					<% end %>
<% if @reviser.try(:essay_type) == "College Essays" %>
					<i class="fa fa-university" aria-hidden="true" style="font-size:60px;color:#45d1b8;"></i>
					<% end %>
<% if @reviser.try(:essay_type) == "Business Papers" %>
					<i class="fa fa-balance-scale" aria-hidden="true" style="font-size:60px;color:#45d1b8;"></i>
					<% end %>
<% if @reviser.try(:essay_type) == "Resumes" %>
					<i class="fa fa-newspaper-o" aria-hidden="true" style="font-size:60px;color:#45d1b8;"></i>
					<% end %>
<% if @reviser.try(:essay_type) == "High-School Essays" %>
					<i class="fa fa-pencil-square" aria-hidden="true" style="font-size:60px;color:#45d1b8;"></i>
					<% end %>
<% if @reviser.try(:essay_type) == "Scholarship Essays" %>
					<i class="fa fa-money" aria-hidden="true" style="font-size:60px;color:#45d1b8;"></i>
					<% end %>

app/views/revisers/_form.html.erb
<!-- http://localhost:3000/revisers/new -->

<div class="panel panel-default">
	<div class="panel-heading">
		멘토가 되어주셔서 감사합니다! 친절한 상담 부탁드립니다!
	</div>
	<div class="panel-body">
		<div class="container3">
			<%= form_for @reviser do |f| %>
			<% if @reviser.errors.any? %>
							<h2 class="error-message">Errors:</h2>
							<ul>
								<% @reviser.errors.full_messages.each do |message| %>
								<li class="error-message"><%= message %></li>
								<% end %>
							</ul>
							<% end %>
			<div class="row">
				<div class="col-md-12">
					<div class="form-group" style="margin-bottom:0;">
						<label>Paypal Email Account(해외에 계신 선배님들을 위해 페이팔 결제를 시행하고 있습니다.)</label>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-md-4">
					<div class="form-group">
						<!-- <label>Paypal Account (You need Paypayl account to receive money)</label> -->
						<%= f.text_field :paypal, :class => 'form-control', :placeholder => "Your Paypal Account"%>
					</div>
				</div>
			</div>
							<!-- <div class="row">
								<div class="col-md-4 select">
									<div class="form-group">
										<label>Max amount of pages you will grade?</label>
										<%= f.select :max_pages, [["500 - 1page",500],["1000 - 2page",1000],["1500 - 3page",1500],["2000 - 5page",2000],["2500 - 6page",2500],["3000 - 7page",3000],["3500 - 8page",3500],["4000 - 9page",4000],["4500 - 10page",4500],["5000 - 11page",5000],["5500+ - 12page+",5500]], prompt: "select..", class: "form-control"  %>
									</div>
								</div>
									<div class="col-md-4 select">
										<div class="form-group">
											<label>Average Time to revise a page (mins)</label>
											<%= f.select :average_time, [["10-15","10-15"],["15-20","15-20"],["20-25","20-25"],["25-30","25-30"],["30-35","30-35"],["35+","35+"]], prompt: "select..", class: "form-control" %>
										</div>
									</div>
								</div> -->
				<div class="row">
					<div class="col-md-3">
						<div class="form-group">
							<label>Price per Hour of your time</label>
							<div class="input-group">
								<div class="input-group-addon">$</div>

								<%= f.select :price_per, [["30","30"],["40","40"],["50","50"],["60","60"],["70","70"],["80","80"],["90","90"],["100","100"]], prompt: "Select Price", class: "form-control" %>

									<!-- <%= f.text_field :price_per, placeholder: "ex. $10", class: "textbox-med" %> -->
							</div>
						</div>
					</div>
				</div>
			<!-- <div class="row">
				<div class="form-group">
					<label>Message to Mentees</label>
					<%= f.text_area :description, rows: 5, placeholder: "Explain your experiences of your categories!", class: "form-control" %>
				</div>
			</div> -->


			<!-- <div class="row">
				<div class="form-group">
					<%= f.check_box :active %> 프로필 공개
				</div>
			</div> -->


			<div class="row">

				<div class="col-md-4 actions">
					<%= f.submit "저장", class: "btn btn-large btn-primary" %>
					<% end %>

				</div>
			</div>
		</div>
	</div>
</div>

app/views/revisers/_userportrait.html.erb
<div class="reviser-posts-wrapper">
  <div class="post">
    <div id="contain-pic">
      <div class="thumbnail-reviser">
       <% if @reviser.user.uid? %>
       <%= image_tag "http://graph.facebook.com/#{@reviser.user.uid}/picture?type=large", :id => "image-tag", class: "portrait" %>
       <% else %>
       <%= image_tag @reviser.user.avatar.url(:medium), :id => "image-tag", class: "portrait" %>
       <% end %>
     </div>
   </div>

   <!-- Reviews stars overall-->



  <div class="row">
    <div class="user-name">
     <%= truncate( @reviser.user.fullname, length:20) %>
   </div>
 </div>
 <div class="post-bottom">
  <div class="caption">

    <div class="row">
      <div class="comment-form col-sm-12">
        Univ: <%= truncate( @reviser.user.school, length: 25) %>

      </div>
    </div>
    <div class="row">
      <div class="comment-form col-sm-12">
      Major: <%= truncate( @reviser.user.major, length: 24) %>
      </div>


    </div>


  </div>
  <div class="comments" >

  </div>

</div>

</div>
</div>

app/views/revisers/create.html.erb
<h1>Revisers#create</h1>
<p>Find me in app/views/revisers/create.html.erb</p>

app/views/revisers/edit.html.erb
<%= render 'form' %>

app/views/revisers/index.html.erb
<%= render 'shared/profileNavbar' %>
<div class="container3" style="min-width:900px;">
<div class="position-col" style="height:100%;">


	<div class="col-xs-8 " style="margin-top:100px;min-width:700px;margin:0 auto;float:none;">
		<div class="display-revisers" style="border-color:#DDDDDD;border-width:5px; border-style: solid;border-radius:5px;background-color:#DDDDDD;">

			<div class="panel-heading" style="color:white;background-color:#45d1b8;border-radius:5px;font-size:20px;">
				Your Registered Reviser Types
			</div>



			<div class="panel-body" style="background-color:#DDDDDD;">
			<div class="row">
			<div class="" style="border-radius:10px;background-color:white;border-style:solid;border-color:white;">
				<p style="font-size:19px;margin:40px;">You may add up to 6 different types of revising methods. It is advised that you have good knowledge on the subject before applying as your ratings will be applied permanently from other users. You may update or add more reviser types/methods.</p>
				</div>
			</div>
			<% @revisers.each do |reviser| %>
			<%= link_to edit_reviser_path(reviser) do %>
				<div class="row" style="background-color:white;border-radius:15px;margin-top:10px;color:black;">
					<div class="col-xs-1">
					<%= render 'shared/essayicons', reviser: reviser %>
					</div>
					<div class="col-xs-8" style="margin-left:10px;">
					<h2 style=""><%= reviser.essay_type %></h2>
					</div>
					<div class="col-xs-2" style="">
					</div>
				</div>
			<% end %>
			<% end %>
			</div>
			<%= link_to "Add Reviesr Type", new_reviser_path(@reviser), class: "btn btn-primary" %>
		</div>
	</div>


</div>
</div>

app/views/revisers/new.html.erb
<%= render 'form' %>

app/views/revisers/show.html.erb
<!--  -->
<script>

								$(function() {
  $('.directUpload').find("input:file").each(function(i, elem) {
    var fileInput    = $(elem);
    var form         = $(fileInput.parents('form:first'));
    var submitButton = form.find('input[type="submit"]');
    var progressBar  = $("<div class='bar'></div>");
    var barContainer = $("<div class='progress'></div>").append(progressBar);
    fileInput.after(barContainer);
  });
});
								</script>

<div class="container3">
	<div class="panel panel-default">
		<div class="panel-body">

			<br>
			<div class="row">
				<div class="col-md-12">
					<div class="row">
						<div class="col-md-3 text-center">
							<%= render "userportrait" %>


						</div>

						<div class="col-md-7">
							<div class="row">
								<div class="col-sm-12 reservation-description">
								선배님과 메세지를 주고 받으셨나요?  <br>
								결제를 하시기 전에 상담시간을 예약하시기 바랍니다! :) <br>
								*현재 베타 서비스이기 때문에 수수료는 받지 않습니다.(페이팔로 '송금')
								</div>
							</div>

							<div class="row text-center">
								<div class="col-sm-12 date-time-inputs">
									<h>  </h>

								</div>
							</div>


							<%= form_for([@reviser, @reviser.reservations.new]) do |f| %>


							<!-- <div class="row text-center">
								<div class="col-sm-6 date-time-inputs">
									<label>Due Date</label>
									<%= f.text_field :due_date, placeholder: "Select a Date" %>
								</div>
							</div>
							<br>

							<%= f.text_area :rubric, rows: 5, placeholder: 'Explain how you want your paper revised!
							"Hello! I am looking to go to school at "school-name" and would like some revisions on my paper. My rubric asks me to write a 500 word essay describing my personality, why I would be good fit.  Can you show me what more I need to talk about and help with grammer, spelling, and stronger words that would make my essay greater!?, Thank You!!"   ', class: "form-control" %>
 -->


							<br>
							<div class="row text-center">
								<!-- <div class="col-sm-5 date-time-inputs">
									<label>Document</label>
								<%= f.file_field :document, class: 'file'%>


								</div>
								<script type="text/javascript">
									 $(":file").filestyle({buttonName: "btn-primary", iconName: "fa fa-paper", buttonText: "Choose Word Doc", input: false});
								</script> -->


								<div class="col-sm-6">
									<%= render 'reservations/form', f: f %>
								</div>

								<div class="col-sm-6 float-right">
									<div class="row">
										+ Paypal Transaction Fees(3.9%) <br>
										<a href="https://www.paypal.com/webapps/mpp/paypal-fees">About Paypal Fees</a>
									</div>

								</div>

							</div>
							<%= f.submit "Send Now", class: "btn btn-primary", style: "float:right;margin-top:20px;" %>
							<% end %>

							<!-- <div class="row" style="margin-top:50px;">
								<div class="col-md-12">
									<h3>Reviews <span id="average_rating"></span>(<%= @reviews.count %>)</h3>
									<div class="container">
										<div>
											<%= render 'reviews/form' %>

											<%= render 'reviews/form' if @booked && !@hasReview %>
										</div>
										<div>
											<%= render 'reviews/list' %>
										</div>
									</div>
								</div>
							</div> -->

							<script>
								$('#average_rating').raty({
									path: '/assets',
									readOnly: true,
									score: <%= @reviser.average_rating %>
								});
							</script>
						</div>


					</div>




				</div>
			</div>
		</div>
	</div>
</div>

app/views/revisers/update.html.erb
<h1>Revisers#update</h1>
<p>Find me in app/views/revisers/update.html.erb</p>