config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'pages#home'

  devise_for :users,
       :path => '' ,
       :path_names => {:sign_in => 'login', :sign_out => 'logout', :edit => 'profile'},
       :controllers => {:omniauth_callbacks => 'omniauth_callbacks',
                :registrations => 'registrations'
              }


 resources :users, only: [:index, :show] do

 end
 resources :revisers
  # get '/premium/', to: 'revisers#show'
 resources :photos
 resources :pages

 #make sure to change this to user!!! instead of reservations!!!
resources :reviser do
  resources :reservations, only: [:create, :edit, :update]
end


get '/preload' => 'reservations#preload'
get '/preview' => 'reservations#preview'

post '/sent' => 'reservations#sent'
get '/sent' => 'reservations#sent'

post '/notify' => 'reservations#notify'
# get '/mypayments' => 'reservations#your_essays'
get '/received' => 'reservations#received'



get '/school_list' => 'pages#school_list'
get '/about' => 'pages#about'

get '/mentor' => 'pages#mentor'
# get '/payment' => 'pages#payment'
# get '/revisers/11', to: 'patients#show', as: 'payment'

get '/how-to-use/kr' => 'pages#korea'
get '/how-to-use/en' => 'pages#english'
get '/how-to-use/jp' => 'pages#japan'
get '/how-to-use/ch' => 'pages#china'





resources :revisers do
  resources :reviews, only: [:create, :destroy]
end


 resources :suggestions do
  get :autocomplete_user_country, :on => :collection
  get :autocomplete_user_company_name, :on => :collection

  get :autocomplete_user_city, :on => :collection
  get :autocomplete_user_school, :on => :collection
  get :autocomplete_user_major, :on => :collection
 end



 # Community
 resources :boards do
   resources :posts do
       resources :comments
   end
 end
 resources :posts do
     resources :comments
   end

# Messages

 resources :conversations, only: [:index, :show, :destroy] do
   member do
     post :reply
   end
 end
 resources :conversations, only: [:index, :show, :destroy] do
   member do
     post :restore
   end
 end
 resources :conversations, only: [:index, :show, :destroy] do
     collection do
       delete :empty_trash
     end
   end

 resources :conversations, only: [:index, :show, :destroy] do
   member do
     post :mark_as_read
   end
 end
 resources :messages, only: [:new, :create]



 resources :posts do
  resources :comments
  resources :places
end



end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
    before_filter :authenticate_user!
    before_action :get_mailbox
    before_action :get_conversation, except: [:index, :empty_trash]
    before_action :get_box, only: [:index]
    before_action :autocomplete
  def index
    if @box.eql? "inbox"
      @conversations = @mailbox.inbox
    elsif @box.eql? "sent"
      @conversations = @mailbox.sentbox
    else
      @conversations = @mailbox.trash
    end

    @conversations = @conversations.paginate(page: params[:page], per_page: 10)
  end

  def show

  end
  def reply
    current_user.reply_to_conversation(@conversation, params[:body])
    flash[:success] = 'Reply sent'
    redirect_to conversation_path(@conversation)
    # if current_user.access == false
    #   if current_user.messages.where("created_at::date = ?", Date.today).count >= 10
    #     respond_to do |format|
    #       format.html { redirect_to premium_path, notice: 'Want to send more Messages? Become Premium member!' }
    #       format.json { head :no_content }
    #     end
    #   else
    #     current_user.reply_to_conversation(@conversation, params[:body])
    #     flash[:success] = 'Reply sent'
    #     redirect_to conversation_path(@conversation)
    #   end
    #
    # else
    #   current_user.reply_to_conversation(@conversation, params[:body])
    #   flash[:success] = 'Reply sent'
    #   redirect_to conversation_path(@conversation)
    # end
  end
  # def reply
  #   current_user.reply_to_conversation(@conversation, params[:body])
  #   flash[:success] = 'Reply sent'
  #   redirect_to conversation_path(@conversation)
  # end
  def destroy
    @conversation.move_to_trash(current_user)
    flash[:success] = 'The conversation was moved to trash.'
    redirect_to conversations_path
  end

  def restore
    @conversation.untrash(current_user)
    flash[:success] = 'The conversation was restored.'
    redirect_to conversations_path
  end

  def empty_trash
    @mailbox.trash.each do |conversation|
      conversation.receipts_for(current_user).update_all(deleted: true)
    end
    flash[:success] = 'Your trash was cleaned!'
    redirect_to conversations_path
  end


  def mark_as_read
    @conversation.mark_as_read(current_user)
    flash[:success] = 'The conversation was marked as read.'
    redirect_to conversations_path
  end
  private

  def get_mailbox
    @mailbox ||= current_user.mailbox
  end

  def get_conversation
    @conversation ||= @mailbox.conversations.find(params[:id])
  end

  def get_box
    if params[:box].blank? or !["inbox","sent","trash"].include?(params[:box])
      params[:box] = 'inbox'
    end
    @box = params[:box]
  end


  def autocomplete

    @search = User.ransack(params[:q])
    @user = @search.result.order("created_at DESC").to_a.uniq

    @results = @search.result
    @arrUsers = @results.to_a

  end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
  def mailbox_section(title, current_box, opts = {})
    opts[:class] = opts.fetch(:class, '')
    opts[:class] += ' active' if title.downcase == current_box
    content_tag :li, link_to(title.capitalize, conversations_path(box: title.downcase)), opts
  end



  def unread_messages_count
    # how to get the number of unread messages for the current user
    # using mailboxer
    mailbox.inbox(:unread => true).count(:id, :distinct => true)
  end
end

app/views/conversations/_conversation.html.erb
<div class="container3">


  <li class="list-group-item clearfix" style="margin-bottom:1rem;">
    Chatting with <strong>

      <% conversation.participants.each do |r| %>
      <% unless r == current_user %>
      <a href="/users/<%= r.id %>"><%= r.fullname %></a>
      <% end %>

      <% end %>

    </strong> <br>




    <div class="btn-group-vertical pull-right">
      <% if conversation.is_trashed?(current_user) %>
        <%= link_to 'Restore', restore_conversation_path(conversation), class: 'btn btn-xs btn-info', method: :post %>
      <% else %>
        <%= link_to 'Move to trash', conversation_path(conversation), class: 'btn btn-xs btn-danger', method: :delete,
                    data: {confirm: 'Are you sure?'} %>
<br>
        <% if conversation.is_unread?(current_user) %>
          <%= link_to 'Mark as read', mark_as_read_conversation_path(conversation),
                      class: 'btn btn-xs btn-info', method: :post %>
        <% end %>
      <% end %>
    </div>


<br>

    <%= link_to conversation_path(conversation) do %>
      <!-- Title : <%= conversation.subject  %> -->
      <!-- <%= conversation.last_message.body %> -->
      <p>
        Last Message :
        <%= truncate(conversation.last_message.body, length: 30) %>

        <!-- <% if conversation.last_message.sender == current_user %>
        (Me)
        <% else %> -->
        (<%= conversation.last_message.sender.email %>)
        <!-- <% end %> -->

        (<span class="text-muted"><%= conversation.last_message.created_at.strftime("%-d %B %Y") %></span>)</p>
    <% end %>



  </li>

</div>

app/views/conversations/_participants.html.erb
<% conversation.participants.each do |participant| %>
  <% unless participant == current_user %>

    <a href="/users/<%= participant.id %>"><%= participant.fullname %></a>

  <% end %>

<% end %>

app/views/conversations/index.html.erb
<% if(!user_signed_in?) %>

<% else %>
  <% if current_user.revisers.present? %>

  <% end %>

<% end %>
<br>
<br>
<div class="container3">
<!-- <p><%= link_to 'Start conversation', new_message_path, class: 'btn btn-lg btn-primary' %></p> -->

  <div class="row">
    <div class="col-sm-3">
      <ul class="nav nav-pills nav-stacked">
        <span class="label label-danger pull-left clearfix"><%=unread_messages_count%></span>
<br>


    <%= mailbox_section 'inbox', @box %>

    <%= mailbox_section 'sent', @box %>
    <%= mailbox_section 'trash', @box %>

      </ul>
    </div>

    <div class="col-sm-9">
      <!-- <% if @box == 'trash' %>
        <p><%= link_to 'Empty trash', empty_trash_conversations_path, class: 'btn btn-danger', method: :delete, data: {confirm: 'Are you sure?'} %></p>
      <% end %> -->
      <%= will_paginate %>

      <ul class="list-group">
        <%= render partial: 'conversations/conversation', collection: @conversations %>
      </ul>

    </div>

  </div>
</div>

app/views/conversations/show.html.erb
<% if(!user_signed_in?) %>

<% else %>
  <% if current_user.revisers.present? %>

  <% end %>

<% end %>
<br>
<div class="container3">


  <p style="font-size: 3rem;color: #fff;font-weight: 700;">Chatting With
    <%= render 'conversations/participants', conversation: @conversation %>
  </p>

  <div class="panel panel-default">
    <div class="panel-heading"><%= @conversation.subject %></div>

    <div class="panel-body">
      <div class="messages">
        <% @conversation.receipts_for(current_user).order(:created_at).each do |receipt| %>
          <div class="media">
            <% message = receipt.message %>
            <div class="media-left">
              <!-- <%= message.sender.email %> -->
              <%= message.sender.fullname %>

            </div>

            <div class="media-body">
              <h6 class="media-heading"><%= message.sender.fullname %>
                says at <%= message.created_at.strftime("%-d %B %Y") %></h6>
              <%= markdownify message.body %>
            </div>
          </div>
        <% end %>
        <%= form_tag reply_conversation_path(@conversation), method: :post do %>
          <div class="form-group">

            <%= text_area_tag 'body', nil, cols: 3, class: 'form-control', placeholder: 'Type something...', required: true %>
          </div>
          <%= submit_tag "Send Message", class: 'btn btn-primary' %>
          <a href="/conversations" class="btn btn-primary">Go Back</a>

        <% end %>


      </div>

    </div>
  </div>

</div>