config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'pages#home'

  devise_for :users,
       :path => '' ,
       :path_names => {:sign_in => 'login', :sign_out => 'logout', :edit => 'profile'},
       :controllers => {:omniauth_callbacks => 'omniauth_callbacks',
                :registrations => 'registrations'
              }


 resources :users, only: [:index, :show] do

 end
 resources :revisers
  # get '/premium/', to: 'revisers#show'
 resources :photos
 resources :pages

 #make sure to change this to user!!! instead of reservations!!!
resources :reviser do
  resources :reservations, only: [:create, :edit, :update]
end


get '/preload' => 'reservations#preload'
get '/preview' => 'reservations#preview'

post '/sent' => 'reservations#sent'
get '/sent' => 'reservations#sent'

post '/notify' => 'reservations#notify'
# get '/mypayments' => 'reservations#your_essays'
get '/received' => 'reservations#received'



get '/school_list' => 'pages#school_list'
get '/about' => 'pages#about'

get '/mentor' => 'pages#mentor'
# get '/payment' => 'pages#payment'
# get '/revisers/11', to: 'patients#show', as: 'payment'

get '/how-to-use/kr' => 'pages#korea'
get '/how-to-use/en' => 'pages#english'
get '/how-to-use/jp' => 'pages#japan'
get '/how-to-use/ch' => 'pages#china'





resources :revisers do
  resources :reviews, only: [:create, :destroy]
end


 resources :suggestions do
  get :autocomplete_user_country, :on => :collection
  get :autocomplete_user_company_name, :on => :collection

  get :autocomplete_user_city, :on => :collection
  get :autocomplete_user_school, :on => :collection
  get :autocomplete_user_major, :on => :collection
 end



 # Community
 resources :boards do
   resources :posts do
       resources :comments
   end
 end
 resources :posts do
     resources :comments
   end

# Messages

 resources :conversations, only: [:index, :show, :destroy] do
   member do
     post :reply
   end
 end
 resources :conversations, only: [:index, :show, :destroy] do
   member do
     post :restore
   end
 end
 resources :conversations, only: [:index, :show, :destroy] do
     collection do
       delete :empty_trash
     end
   end

 resources :conversations, only: [:index, :show, :destroy] do
   member do
     post :mark_as_read
   end
 end
 resources :messages, only: [:new, :create]



 resources :posts do
  resources :comments
  resources :places
end



end

app/views/shared/_devisemes.html.erb
<% unless resource.errors.empty? %>

<script type="text/javascript">
<% resource.errors.full_messages.each do |msg| %>
toastr.error("<%= msg %>")
<% end %>
</script>
<% end %>

app/views/shared/_essayicons.html.erb
<% if reviser.try(:essay_type) == "College Applications" %>
					<i class="fa fa-wpforms" aria-hidden="true" style="font-size:60px;color:#45d1b8;"></i>
					<% end %>
<% if reviser.try(:essay_type) == "College Essays" %>
					<i class="fa fa-university" aria-hidden="true" style="font-size:60px;color:#45d1b8;"></i>
					<% end %>
<% if reviser.try(:essay_type) == "Business Papers" %>
					<i class="fa fa-balance-scale" aria-hidden="true" style="font-size:60px;color:#45d1b8;"></i>
					<% end %>
<% if reviser.try(:essay_type) == "Resumes" %>
					<i class="fa fa-newspaper-o" aria-hidden="true" style="font-size:60px;color:#45d1b8;"></i>
					<% end %>
<% if reviser.try(:essay_type) == "High-School Essays" %>
					<i class="fa fa-pencil-square" aria-hidden="true" style="font-size:60px;color:#45d1b8;"></i>
					<% end %>
<% if reviser.try(:essay_type) == "Scholarship Essays" %>
					<i class="fa fa-money" aria-hidden="true" style="font-size:60px;color:#45d1b8;"></i>
					<% end %>

app/views/shared/_essaypageicons.html.erb
<% if essay.try(:essay_type) == "College Applications" %>
					<i class="fa fa-wpforms" aria-hidden="true" style="font-size:60px;color:#45d1b8;"></i>
					<% end %>
<% if essay.try(:essay_type) == "College Essays" %>
					<i class="fa fa-university" aria-hidden="true" style="font-size:60px;color:#45d1b8;"></i>
					<% end %>
<% if essay.try(:essay_type) == "Business Papers" %>
					<i class="fa fa-balance-scale" aria-hidden="true" style="font-size:60px;color:#45d1b8;"></i>
					<% end %>
<% if essay.try(:essay_type) == "Resumes" %>
					<i class="fa fa-newspaper-o" aria-hidden="true" style="font-size:60px;color:#45d1b8;"></i>
					<% end %>
<% if essay.try(:essay_type) == "High-School Essays" %>
					<i class="fa fa-pencil-square" aria-hidden="true" style="font-size:60px;color:#45d1b8;"></i>
					<% end %>
<% if essay.try(:essay_type) == "Scholarship Essays" %>
					<i class="fa fa-money" aria-hidden="true" style="font-size:60px;color:#45d1b8;"></i>
					<% end %>

app/views/shared/_hello.html.erb
<%= image_tag @post.image.url(:medium) %>
<div> </div>

app/views/shared/_message.html.erb
<% unless flash.empty? %>
<script type="text/javascript">
<% flash.each do |f| %>
	<% type = f[0].to_s.gsub('alert','error').gsub('notice','info') %>
	toastr['<%= type %>']('<%= f[1] %>')
	<% end %>
	</script>
	<% end %>

	

app/views/shared/_navbar.html.erb
  <nav class="navbar navbar-inverse">
    <div class="navbar-header">
    	<button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".js-navbar-collapse">
			<span class="sr-only">Toggle navigation</span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
		</button>

		<a class="navbar-brand navbar-brand-centered" href="/"><%= image_tag('/assets/tweedlelong.png')%></a>

	</div>

	<div class="collapse navbar-collapse js-navbar-collapse">

        <ul class="nav navbar-nav navbar-right" >
          <!-- <li style="color:#337ab7;">전체 멘토 수 : <%= @mentors %>명, 전체 멘티 수 : <%= @mentees %>명</li> -->
          <% if(!user_signed_in?) %>
           <li> <%= link_to "Log In", new_user_session_path %> </li>
           <li> <%= link_to "Sign Up", new_user_registration_path %> </li>
           <% else %>
            <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-expanded="false">

                <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">

                <li><%= link_to "My Profile", user_path(current_user) %></li>
                <li><%= link_to "Edit Profile", edit_user_registration_path %></li>

                 <li><a href="/sent">Requests Sent</a></li>
                <li><a href="/received">Requests Received</a></li>
                <!-- <li><a href="/mypayments">My Payments</a></li> -->

                <li role="separator" class="nav-divider"></li>

                <li><%= link_to "Log Out", destroy_user_session_path, method: :get %></li>
              </ul>
            </li>
      <% end %>

        <% if user_signed_in? %>
              <li>
                <a href="/conversations"><span class="label label-danger"><%=unread_messages_count%></span><i class="fa fa-envelope-o" aria-hidden="true"></i> Messages</a>
              </li>


            <% else %>


            <% end %>
      </ul>
	</div><!-- /.nav-collapse -->
  </nav>

app/views/shared/_navbar2.html.erb
<nav class="navbar navbar-default" style="box-shadow: 0px 1px 4px 0px rgba(0,0,0,0.75);">
<div class="container">
<!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".js-navbar-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>

  </div>

<!-- Collect the nav links, forms, and other content for toggling -->
<div class="collapse navbar-collapse js-navbar-collapse">
  <ul class="nav navbar-nav" style = "width:100%;">

    <li><a href="/users?utf8=%E2%9C%93&q%5Bcountry_cont%5D=&q%5Bcity_cont%5D=&q%5Bschool_cont%5D=&q%5Bmajor_cont%5D=&commit=Search">Search Profile</a></li>
    <li><a href="/school_list">Categories<%= image_tag('/assets/new.gif')%></a></li>

    <li class="dropdown">

      <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="false" aria-expanded="false">Talks&Tips!<%= image_tag('/assets/new.gif')%><span class="caret"></span></a>
      <ul class="dropdown-menu" role="menu">
        <li><a href="/boards/1">Seoul<%= image_tag('/assets/new.gif')%></a></li>
        <li><a href="/boards/2">Japan<%= image_tag('/assets/new.gif')%></a></li>

        <li><a href="/boards/3">Europe<%= image_tag('/assets/new.gif')%></a></li>

        <li><a href="/boards/4">USA<%= image_tag('/assets/new.gif')%></a></li>



        <!-- <li><a href="/boards/4">For College Students<%= image_tag('/assets/new.gif')%></a></li>
        <li><a href="/boards/5">For Parents<%= image_tag('/assets/new.gif')%></a></li> -->

        <!-- <li class="nav-divider"></li>
        <li><a href="/boards/6">Tutoring Requests<%= image_tag('/assets/new.gif')%></a></li> -->


      </ul>
    </li>
    <!-- <li><a href="/boards/7">Community</a></li> -->


    <!-- <li class="dropdown">

      <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="false" aria-expanded="false">이용방법/How to Use<span class="caret"></span></a>
      <ul class="dropdown-menu" role="menu">

        <li><a href="/how-to-use/kr">한국어</a></li>
        <li><a href="/how-to-use/en">English</a></li>
        <li><a href="/how-to-use/jp">日本語</a></li>
        <li><a href="/how-to-use/ch">中文</a></li>


        <% if user_signed_in? %>
        <% else %>
        <% end %>

        <li><a href="/boards/4">For College Students<%= image_tag('/assets/new.gif')%></a></li>
        <li><a href="/boards/5">For Parents<%= image_tag('/assets/new.gif')%></a></li>

        <li class="nav-divider"></li>
        <li><a href="/premium">Go Premium</a></li>
        <li><a href="/boards/6">Consulting Requests<%= image_tag('/assets/new.gif')%></a></li>


      </ul>
    </li> -->
    <!-- <li><a href="/about">About</a></li> -->

    
    <!-- <li><a href="/mentor">멘토가 되는 법</a></li> -->

    <!-- <li><a href="https://www.facebook.com/Tweedlemate-1636012746729501/">FaceBook Page</a></li> -->
    <li><a href="/how-to-use/kr">Contact</a></li>

  </ul>
</div><!-- /.navbar-collapse -->
</div><!-- /.container-fluid -->
</nav>

app/views/shared/_profileNavbar.html.erb
<nav class="navbar-sm">
<div class="table">
  <ul class="nav" style="background-color:#DDDDDD;text-align: center;">
    <!-- <li style="display: inline-block;"><a style="color:grey;" href="/conversations">Inbox</a></li> -->
    <li style="display: inline-block;"><a style="color:grey;" href="/sent">Requests Sent</a></li>
    <li style="display: inline-block;"><a style="color:grey;" href="/received">Requests Received</a></li>
    <!-- <% @k = current_user.revisers.last%> -->

    <!-- <li style="display: inline-block;"><%= link_to "Edit Mentor Service", edit_reviser_path(@k), style: "color:grey;"%></li> -->

  </ul>
  </div>
</nav>